### ISSUE TITLE
Adding a queue

### ISSUE THREAD

**Issue by ImTravis** [teozfrank/DuelMe#100]
Just a little idea to add a queue when you can join a queue and you can find another random player in the queue and then a duel starts.

**Comment by teozfrank** [comment]
Good idea, I will most certainly look into it. What command would you put this into? something like /duel join?

**Comment by teozfrank** [comment]
@snak3pvp Would you be interested in testing this feature with me? I have a first test version we can try out before I release it online.

**Comment by snak3pvp** [comment]
Sure!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
