### ISSUE TITLE
New suggestions and fixes

### ISSUE THREAD

**Issue by LudnicaKiller** [teozfrank/DuelMe#103]
When someone click on sign of duel arena that he is in queue or in arena.

When some player is in god mode before duel arena starts and it starts players can't fight. Make that it exits from god mode and vanish mode, it's only moving from creative to survival, thats ok.

When I ignore someone duel request, he doesn't get any message that I don't want to duel.
Make it possible that GUI is translatable (accepting and declining duel request).

When I type some command in duel it spams 2 times same message (http://prntscr.com/jy9ax0)

Can you make, when some player is killed that it writes down that in chat, or in config.yml "duelwinner:" make possible to add etc. %opponent%

**Comment by LudnicaKiller** [comment]
@teozfrank There is no more debug messages but you need to add one more message into the messages.yml that is missing: "You have been removed from the duel queue."

**Comment by teozfrank** [comment]
Ahhh okay, I will add that.

**Comment by teozfrank** [comment]
Over 2 years later, Its now added! lol sorry!

**Comment by teozfrank** [comment]
https://www.spigotmc.org/resources/duelme-beta-spigot-1-8-8-1-16-4-only.541/update?update=378172
