### ISSUE TITLE
Disabling McMMO during duel suggestion

### ISSUE THREAD

**Issue by Flexxxxx** [teozfrank/DuelMe#106]
Since this plugin appears to be intended as a way to battle others on an even slate, it would be awesome to have McMMO perks, passives and abilities disable or be ignored during combat. This would allow servers with McMMO installed to fully utilise this plugin by allowing all players to have fair fights.

Could have it as a true/false toggle in the config.

**Comment by teozfrank** [comment]
Just place the duel arenas in a world where McMMo is disabled.
