### ISSUE TITLE
DuelMe "DuelTimer" > enable/disable from ActionBar

### ISSUE THREAD

**Issue by Fawkd** [teozfrank/DuelMe#108]
Hi,

It's been a long time since I have come here with an issue. Or rather like this time, a suggestion.

**Situation:**
I am currently using a plugin to display health of players and mobs called "ActionHealth". This plugin works so that as long as you hover/keep hitting a target (this case a player in duel) it keeps updating their HP values in the actionbar. 

**Issue:**
Since DuelMe uses actionbar for dueltimer it keeps flickering between the two.

**Possible solutions/suggestions:**
Toggleable dueltimer: false/true
BossBar dueltimer: false/true (?)

Thanks in advance, also good job with the queue system, cannot wait for stable version of it!

Keep it up!

Regards,
Fawked

**Comment by teozfrank** [comment]
Latest dev build has the option to disable the actionbar. Full details will be a available on new jenkins server soon.
