### ISSUE TITLE
Health set to 20 (10 hearts) on join colliding with plugins such as "LifeEssence"

### ISSUE THREAD

**Issue by Fawkd** [teozfrank/DuelMe#109]
Hello,

I noticed that since the "heal" feature was added beginning of the duel it actually sets the health to 10 hearts instead of actually healing the player. 

Here's a video to showcase the issue:
[https://streamable.com/r1nlx](url)

There are no errors whatsoever in console.

Regards,
Fawked

**Comment by teozfrank** [comment]
This is a bug, there wouldnt be errors in the console as the health is set to a fixed value when the duel starts instead of getting the max health set for a player and using that instead. Will be fixed for the next relelase, thanks for reporting :)

**Comment by teozfrank** [comment]
Should be fixed on the latest pre-release here -> https://github.com/teozfrank/DuelMe/releases/tag/0.9-pre

**Comment by teozfrank** [comment]
Reported as fixed, closing.
