### ISSUE TITLE
From members

### ISSUE THREAD

**Issue by ToxicWaste** [teozfrank/DuelMe#11]
getting these messages from members on my site:

i just noticed something else i am missing after the duel. i had 4 levels of xp and they are gone.

i went into a duel with maxmighty and i had a diamond pick in my inventory. it was about halfway used with silk touch I, efficiency IV, and unbreaking III on it. after the duel everything in my inventory was returned except for the diamond pickaxe. i attatched a pic of my inventory after the duel if that helps at all.  

this is a staff member they have no reason to lie but the second one i expect he is mistaken..

List of plug ins

![plugins](https://cloud.githubusercontent.com/assets/1341429/5562584/fdccc274-8dee-11e4-9fca-d874c3290d4c.PNG)

**Comment by teozfrank** [comment]
Could you please test the latest version of the plugin. I have recoded the player storage and fixed the issues with multiple inventories being stored.

**Comment by teozfrank** [comment]
Closing as no response was made, please recreate this issue if it still persists.
