### ISSUE TITLE
DuelMe Debug bug and messages.yml

### ISSUE THREAD

**Issue by LudnicaKiller** [teozfrank/DuelMe#111]
Hello,
I have the latest version of this plugin but in this version debug is turned on and can't turn it off.
This is the queue update and when someone clicks on sign it writes "[DuelMe] [Debug] Right click wall sign yay!.". And make this debugging back again to "true or false" in config.yml

Can you make this messages translatable in messages.yml:
1. you are already in the queue
2. you have joined the queue, there is currently 1 in the queue
3. There is not enough players to start a duel yet

I would really like that you do this asap,
Thanks in advance

**Comment by teozfrank** [comment]
Done, I cannot see the message  "[DuelMe] [Debug] Right click wall sign yay!." anywhere in the code, can you please check the latest release here and check does it still show? -> https://www.spigotmc.org/resources/duelme-beta-spigot-1-8-8-1-12-2-only.541/update?update=252733
