### ISSUE TITLE
DuelMe v0.19.1 Crash error

### ISSUE THREAD

**Issue by LudnicaKiller** [teozfrank/DuelMe#113]
Hello,
Everyone can crash server with spamming with right clicks on signs.
Console error: https://pastebin.com/BbvaA98y

This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by teozfrank** [comment]
Both of those errors seem unrelated? Can you please explain what happens step by step?

**Comment by LudnicaKiller** [comment]
I’m not using your plugin because of lot of errors and glitches and you’re not active.
There are so many bypasses to get other items in the arena

**Comment by teozfrank** [comment]
Care to share some of the errors / glitches? Yes I have been quite busy with my own job but I am trying to get back into getting the plugin back into a workable state. :)

**Comment by LudnicaKiller** [comment]
I don’t remember anything, i stopped using it 3 month ago..

Lijep pozdrav,
LudnicaKiller,
vlasnik SarmaCraft hrvatskog Minecraft servera

17.09.2019., u 00:02, korisnik Frank Fallon <notifications@github.com> je napisao:

**Comment by teozfrank** [comment]
Ok no problem thanks.
