### ISSUE TITLE
DuelMe V0.19.1 | Deathcause (player) not displaying

### ISSUE THREAD

**Issue by LudnicaKiller** [teozfrank/DuelMe#114]
I have a problem, I'm not receiving in chat who won the DuelMe battle. I have tried reseting messages.yml but nothing changes and still doesn't work..

This message: 
deathcause:
player: '&6%player% &fje ubijen u duelu od &6%killer%&f!'

config.yml: https://pastebin.com/4mRH886s
duelarenas.yml: https://pastebin.com/S1tipwf4
messages.yml: https://pastebin.com/mM9pH63N

**Comment by teozfrank** [comment]
The only reason this wont show is if the death cause was not by a player.
