### ISSUE TITLE
Error PlayerRespawnEvent DuelMe v0.19.1

### ISSUE THREAD

**Issue by LudnicaKiller** [teozfrank/DuelMe#117]
Error: https://pastebin.com/tNag5x3v
Another error: https://pastebin.com/Pqkmrdxg
PaperSpigot 1.8.8
DuelMe v0.19.1

**Comment by LudnicaKiller** [comment]
*bump*

**Comment by teozfrank** [comment]
Hi, When does this happen? Can you list step by step how you produce this error please?

**Comment by teozfrank** [comment]
Closing as no response made.
