### ISSUE TITLE
org.bukkit.command.CommandException: Unhandled exception executing command 'dueladmin' in plugin DuelMe v0.20-dev

### ISSUE THREAD

**Issue by menoxsk** [teozfrank/DuelMe#118]
Hi, im getting this error
org.bukkit.command.CommandException: Unhandled exception executing command 'dueladmin' in plugin DuelMe v0.20-dev
on 1.14.4 newest paper spigot

**Comment by teozfrank** [comment]
need to see the full stack trace, please provide logs.
