### ISSUE TITLE
cant create arenas

### ISSUE THREAD

**Issue by theshadyonehd** [teozfrank/DuelMe#12]
creating a arena gives no error expect ingame which is "An interal error occurred while attempting to perform this command." Lastest spigot verison

**Comment by teozfrank** [comment]
You are probobly using the latest version of WorldEdit which the plugin does not support, I am releasing an update that should add support for this please test it and confirm does the error still persist.

**Comment by theshadyonehd** [comment]
i am using the lastest worldedit plugin, ill downgrade thanks.

**Comment by teozfrank** [comment]
Support for WorldEdit 6.0 has been added. Older versions of WorldEdit may work but are unsupported.
