### ISSUE TITLE
inventory issue/ new features.

### ISSUE THREAD

**Issue by theshadyonehd** [teozfrank/DuelMe#13]
both players loss their inventory whether they lose or win. I to add this to my factions server, so players can fight other players and then if they will collect the other players items. I think if you will there should be a delay of 30seconds before your teleported out of the arena. this way the other player can pick up the items for the died player. Also I think it would be awesome if you added a delay to the leave command. It only teleports them after 3 seconds if the player does not move.

Config: http://pastebin.com/eEkLxzMY

**Comment by teozfrank** [comment]
Are you using the latest version of the plugin? I recoded the player storage so players should not loose there inventories anymore. I will take leave command delay as a feature request.

**Comment by teozfrank** [comment]
This has been fixed in the latest version, players that loose there items will be restored regardless, another update will fix this in the future, want to get the main system working correctly for now.
