### ISSUE TITLE
Cancel damage instead of saving player on death

### ISSUE THREAD

**Issue by DarkShimy00** [teozfrank/DuelMe#15]
It is less buggy to cancel the damage event if life goes under 0 than saving the player's inventory/xp/hunger on death.

**Comment by teozfrank** [comment]
How is this so? The players data isn't saved when they die, but rather before the player starts dueling with another player. Have you checked the code?

**Comment by DarkShimy00** [comment]
Yes, I checked the code right before opening this issue.

What I mean is that you use `dm.addDeadPlayer(playerUUID);` and then listen to the event `onPlayerRespawn(PlayerRespawnEvent e)` to restore the inventory.

This works but may cause bugs (plugin unloading BEFORE the player has respawned for example). A safer method is to *cancel* the damage event and immediately restore the player's data.

I misspoke but it's sad to see how you react when someone tries to improve the plugin.

**Comment by teozfrank** [comment]
Well if you explained it a little more I wouldn't have been so defensive. I must have missed that so the idea is to prevent players actually dieing so you can prevent this?

**Comment by DarkShimy00** [comment]
You can see what the code would be. The code is simpler. You can get rid of all the "is the player dead? -> put the player in a map --> is the player respawning? --> restore his inventory" code and immediately restore his inventory. Optimized and more reliable.

```
  @EventHandler(priority = EventPriority.NORMAL)
  public void onPlayerDamage(EntityDamageEvent e) {
    Entity entity = e.getEntity();

    if (!(entity instanceof Player)) {
      return;
    }

    if(e.getCause() != EntityDamageEvent.DamageCause.FALL) {
      return;
    }

    DuelManager dm = plugin.getDuelManager();
    Player player = (Player) entity;
    String playerName = player.getName();
    UUID playerUUID = player.getUniqueId();

    if (dm.isInDuel(playerUUID)) {// if the player is in a duel
      DuelArena playersArena = dm.getPlayersArenaByUUID(playerUUID);
      if(playersArena.getDuelState() == DuelState.STARTING) {//if the duel state is starting
        e.setCancelled(true); //cancel the event
      } else if (playersArena.getDuelState() == DuelState.STARTED
          && (player.getHealth() - e.getDamage()) < 1) {
        e.setCancelled(true);

        // Here do all the stuff concerning the duel end, like in onPlayerDeath()
      }
    }
  }
```

**Comment by teozfrank** [comment]
Implemented, thank you for the suggestion!
