### ISSUE TITLE
Not teleporting after duel is over

### ISSUE THREAD

**Issue by sran13** [teozfrank/DuelMe#16]
When a duel is over, the players don't get teleported back to the location they were at. This is happening as the players aren't out of combat when the duel is over so combat log won't let them teleport.

**Comment by teozfrank** [comment]
What version are you using?

**Comment by teozfrank** [comment]
Also you need to disable combat log in the world you have the arenas, its ideal to have a seperate world for these as the plugin can deal with players pvp logging.

**Comment by sran13** [comment]
Disabled CL in the arena world and everything's running smoothly. Thanks!

**Comment by teozfrank** [comment]
Thanks for letting me know! :)
