### ISSUE TITLE
database

### ISSUE THREAD

**Issue by ToxicWaste** [teozfrank/DuelMe#17]
sorry about the other issues i just got back on

ok with the latest version the database saves only the winner and says they have a kill and a death where the loser never got recorded a loss..
This is with one battle digital ninja played meparks.digital won meparks lost the database listed digital with both a kill and a death while meparks was not listed at all..
![duel info](https://cloud.githubusercontent.com/assets/1341429/6241499/b9a5e882-b6e3-11e4-9bde-e8f33bd713ab.PNG)
![duelme database](https://cloud.githubusercontent.com/assets/1341429/6241501/bef98c44-b6e3-11e4-95c5-8e52eb1d901c.PNG)

**Comment by teozfrank** [comment]
Fixed in latest release, thanks for reporting.
