### ISSUE TITLE
database

### ISSUE THREAD

**Issue by ToxicWaste** [teozfrank/DuelMe#18]
updated to the new release erased all data from the database had a duel with me and _babybird_.I won listed her death but did not list my win pic included.
![duelme database1](https://cloud.githubusercontent.com/assets/1341429/6251020/1a41a7f8-b757-11e4-9de4-56f0332d2394.PNG)

**Comment by ToxicWaste** [comment]
http://mc.tuminecraft.com/

still not working wont add kills

**Comment by teozfrank** [comment]
Fixed in the latest build thanks for reporting!
