### ISSUE TITLE
get DuelState is erroneous

### ISSUE THREAD

**Issue by RubeGamerV** [teozfrank/DuelMe#19]
<a href="http://gyazo.com/84091474371f97e30f31c496a486e9b7"><img src="http://i.gyazo.com/84091474371f97e30f31c496a486e9b7.png" /></a>

**Comment by teozfrank** [comment]
I'm assuming your using NetBeans, What version and what version of Java are you compiling with?

**Comment by RubeGamerV** [comment]
is NetBeans 7.4 and i use java jre7

**Comment by teozfrank** [comment]
Ah that explains it, im using IntelliJ and I do not get this error. try replacing da.getDuelState(); with -> da.getDuelState().toString();

**Comment by RubeGamerV** [comment]
i forgot, http://gyazo.com/0505177ed94b73e63605d5773a930529

**Comment by RubeGamerV** [comment]
I fix it, thanks!
