### ISSUE TITLE
Random bugs

### ISSUE THREAD

**Issue by xion87** [teozfrank/DuelMe#20]
i found these bugs
- player randomy spawn in same pos1 instead pos2
- player die with one hit and there is the text "malachiel killed malachiel"....

**Comment by gogobebe2** [comment]
I've experienced these 2 bugs aswell. In addition, when a player kills another player in a duel, it often doesn't end the duel.

**Comment by teozfrank** [comment]
Surely its not truely "random" and it occurs when something specific happens, if you can step me though step by step how this occurs it can help me to determine the problem alot easier.

**Comment by gogobebe2** [comment]
I dueled someone with /duel send <player>. They accepted then we went to the arena which I setup, Then in the arena I killed the player within 15 seconds - Fairly fast after the game started. I just stood there and couldn't get out of the arena. It sent him back but not me. So I just ended the duel and then got back. It also didn't say I won.

I spawned in the same position as the other player one time just by entering the duel.

I havn't experienced dieing in one hit though. I don't think you do anything to modify damage in your plugin so it's probably xion87's problem.

**Comment by xion87** [comment]
Mmm it can be related to Pvp Manager? is a combat tag

**Comment by teozfrank** [comment]
Right I can see a flaw here with using players damage taken as it doesnt take into account players armour, so what I am going to do is rewrite the death system to back the way it was supposed to be and have the plugin force respawn players so we can bypass potential issues I had with the old death system. :)

**Comment by gogobebe2** [comment]
Thanks babe.

**Comment by teozfrank** [comment]
New pre release added, I tested myself on my own dev server, could you test and confirm does it work ok? Note this will only work with spigot 1.8.3.

**Comment by xion87** [comment]
a link?

**Comment by teozfrank** [comment]
https://github.com/teozfrank/DuelMe/releases/tag/0.9.14.3

**Comment by xion87** [comment]
well, if i kill somesone in duel, duel will no end, and i will be stucked in arena.......

**Comment by iZehnny** [comment]
When i try /duel it says
An internal error occurred while attempting to perform this command
help please!

**Comment by teozfrank** [comment]
could you show me the stack trace of the error? look in console when you type that command and pastebin the results please.

**Comment by iZehnny** [comment]
Here is the pastebin from the error An internal error occurred while attempting to perform this command
http://pastebin.com/1Y7RF0hQ

**Comment by iZehnny** [comment]
Here is the link from the error:
http://pastebin.com/1Y7RF0hQ

**Comment by teozfrank** [comment]
It looks like your using an outdated version of spigot, what version are you using?

**Comment by iZehnny** [comment]
Spigot 1.7.10 + 1.8
So you can go on the server with 1.7.10 and 1.8

**Comment by teozfrank** [comment]
Thats the protocol patch or 1.7.10 the API, this plugin will only work with actual 1.8 API and above.

**Comment by teozfrank** [comment]
closed as no replys have been made, you must use the latest version of spigot, version 1.8.7 for the latest releases.
