### ISSUE TITLE
BUGS LOTS FIX PLEASE... 

### ISSUE THREAD

**Issue by TheKBSGamer** [teozfrank/DuelMe#21]
This plugin has so many damn bugs... You're taking your time to fixing them as well. The newest version has a bug where if you're wearing diamond armor the plugin does not register the armor and the player dies when reaching 5 hearts, which is a normal death when not wearing an armor. Also make sure the duel request are not receive when player is in combat, supporting pvpmanager plugin. If this bug is fixed then the plugin is safe and fun to use, atm this is crap and sucks B.

**Comment by teozfrank** [comment]
Do you really have to be so disrespectful in your comments? Report the issue / improvement not copy paste a comment from spigot.

**Comment by TheKBSGamer** [comment]
Is it possible to make the plugin compatible with other version of spigot for example 1.7.10?

**Comment by teozfrank** [comment]
Feel free to modify the code so it is compatible.

**Comment by teozfrank** [comment]
closing issue as this bug has been fixed.
