### ISSUE TITLE
Teleport bug still present and duell are not working correct sometimes

### ISSUE THREAD

**Issue by xion87** [teozfrank/DuelMe#25]
As title say and i have these errors wave using spigot 1.8.8 http://hastebin.com/fufujiwaju.avrasm

**Comment by teozfrank** [comment]
What version of the plugin are you using?

**Comment by xion87** [comment]
DuelMe 0.9.14.11 Beta

**Comment by teozfrank** [comment]
You are a version behind please retest with the latest update -> https://www.spigotmc.org/resources/duelme-beta-spigot-1-8-8-only.541/update?update=37761

**Comment by xion87** [comment]
ah you moved on spigot?  i didn't see that... !

**Comment by teozfrank** [comment]
Yes its been there for over a year xD, I update the spigot plugin first and sometimes forget to update the bukkit dev version.

**Comment by xion87** [comment]
Hi i just tested so:
- player sometimes is teleported under the arena (i got  a flying arena)
- player sometimes teleported on wrong arena (i got 3 arena, player1 is in arena1 and player2 is is in arena2)
errors log http://hastebin.com/raxuyuwoca.avrasm

**Comment by xion87** [comment]
also make a options to disable the gui, is pretty annoying to spam the gui to somesone that is fighting

**Comment by teozfrank** [comment]
Ok, have you set spawnpoints for each arena ?

**Comment by xion87** [comment]
i am restarting it now
yeah my arena file is correct
http://hastebin.com/epidajedow.sm

**Comment by xion87** [comment]
again i have
[14:18:54 INFO]: giancavide issued server command: /duel accept
[14:19:00 INFO]: giancavide issued server command: /duel accept XxGiammisexX
[14:19:27 INFO]: There is no such item with name minecraft:267

**Comment by teozfrank** [comment]
Is it possible for you to send me your arena world so I can test this better? Also I have uploaded a newer version for you to try which should prevent players from being teleported to the wrong arenas or where there is a duel already in progress.

**Comment by xion87** [comment]
I just tried again, same issue, item reward go to loser, wrong arena 
teleport, no errors on console...


Il 05/08/2015 1.04, Frank Fallon ha scritto:

**Comment by teozfrank** [comment]
What arena does the player get teleported to? Is it the same arena each time or a different one?

**Comment by xion87** [comment]
sometimes is the same, sometimes is different

**Comment by xion87** [comment]
also please fix winner cmd that is rewarding lose player.....

**Comment by teozfrank** [comment]
Please try this pre release to see does it resolve your teleportation issues. Players will not be frozen on the start of a duel this is intentional to determine the issue.

https://github.com/teozfrank/DuelMe/releases/tag/0.9.15.4

also please fix winner cmd that is rewarding lose player.....
I cannot reproduce this problem you are having.

**Comment by xion87** [comment]
mm the issue it can be this, i am using kkript that give 1 diamond to killer and maybe is conflicting with it...
My event is this:
on death of player:
	drop 1 diamond at victim
	increase the attacker's level by 1

**Comment by xion87** [comment]
i am askin a thing so i will fix myself, the "reward" item will be given INTO the arena or OUT arena? thank you!

**Comment by xion87** [comment]
i tested and seem to be 0 cases where player go in wrong arena...

**Comment by teozfrank** [comment]
Ok this is confirmed by you and another tester that disabling the freezing fixes those teleporting issues. Great I now know the cause and will work on an alternative way to freeze the players. Should have a version available tomorrow sometime :) Thanks for the help.

On your skript problem. I would just use the winner command to give the player a diamond when they win a duel and use the exp command to give them xp. (if you are using essentials that is) There is no need to use skript to reward the player.

**Comment by xion87** [comment]
hi the problem about skript is that i use that skript as kitpvp plugin, that when a player die from valid reason, it drop a diamond on player place, and in the same server i got also your duel plugin...

**Comment by teozfrank** [comment]
Can you create the arenas in a seperate world and disable the skript in that world?

**Comment by teozfrank** [comment]
Lates update should fix the teleport glitching bug, if this is still present please open a new issue, thanks.
