### ISSUE TITLE
reloading

### ISSUE THREAD

**Issue by jalenk1234** [teozfrank/DuelMe#27]
reloading deletes all arenas

**Comment by teozfrank** [comment]
Could you do the following:

    Stop your server.
    Delete the arenas.yml from the plugins folder.
    Enable debug mode by changing debug enabled in the config.yml to true.
    Start your server.
    Create a few arenas.
    Restart your server.

The arenas should have saved in the arenas.yml file and reloaded after the restart. If this doesnt happen could you send me the logs of your server when you did that.

**Comment by teozfrank** [comment]
also do NOT reload your server, restart it. It should not occur with restarting.
