### ISSUE TITLE
Error logs, doesn't work.

### ISSUE THREAD

**Issue by Loonyy** [teozfrank/DuelMe#28]
http://pastebin.com/ETJs7iJg error log when trying to accept a duel.

http://pastebin.com/kmMpA9pt error log when trying to accept a duel.

**Comment by teozfrank** [comment]
What version of the plugin, version of spigot are you using.

**Comment by Loonytoon1997** [comment]
1.8.8 Spigot and latest version of DuelMe

**Comment by teozfrank** [comment]
Have you tried the latest release on spigot?

**Comment by Walnert** [comment]
Yes, I have.

**Comment by teozfrank** [comment]
Is this issue still present?

**Comment by Loonytoon1997** [comment]
yup

**Comment by teozfrank** [comment]
cant reproduce? Please try a clean install of the latest version.

**Comment by teozfrank** [comment]
closed as old issue, if it still persists please create a new one.
