### ISSUE TITLE
Can you add a feature i believe everyone would like this xD

### ISSUE THREAD

**Issue by AndroidFactionMC** [teozfrank/DuelMe#33]
May you add a feature like with the signs when i do 'LINE: 1 [duelme] LINE:2 ARENA_NAME' Than when i right click i can join that arena i want to do it so when i right click i can join the arena is that possible? Please help!

**Comment by teozfrank** [comment]
With the current system, no it is not possible but I'll consider it for the future.

**Comment by teozfrank** [comment]
Duel signs have been implemented, right clicking a sign will now join a queue for the player. Right now it does not specify the arena but I will look into it at a later stage.
