### ISSUE TITLE
Randomize arenas

### ISSUE THREAD

**Issue by matagin** [teozfrank/DuelMe#35]
I have multiple arenas on my server. Would it be possible to add a feature that randomizes which arena players join? Instead of joining the next available arena in the list in order.

**Comment by gogobebe2** [comment]
This is a good idea and also isn't very hard to implement.

**Comment by matagin** [comment]
Sorry for the late response. Unfortunately, I am not a skilled enough developer.

**Comment by teozfrank** [comment]
Added in latest build, will now randomise arenas if there is more than one setup.
