### ISSUE TITLE
Ignore a duel

### ISSUE THREAD

**Issue by kristiantomov** [teozfrank/DuelMe#37]
When you ignore a duel nothing happens. You cant send another duel after this.

**Comment by gogobebe2** [comment]
It'd be good to include the version of the plugin in which this issue occurred.

**Comment by teozfrank** [comment]
When you ignore a duel it just closes the inventory menu, you cant send another duel request to the same player again but you can to other players.

**Comment by kristiantomov** [comment]
You need to fix that, or at least to put some time after the invite is sent, so you can send another invite.

**Comment by teozfrank** [comment]
to the same person?

**Comment by teozfrank** [comment]
Closing as no response was made, if you want this still to be implemented please create a new issue.
