### ISSUE TITLE
Duels not ending

### ISSUE THREAD

**Issue by Peter234679** [teozfrank/DuelMe#39]
When a duel starts and one of the players gets killed the timer continues to count down but there is no one in the arena to fight. Then after the timer runs out the one player who was still in the arena is teleported back to the spawn and is given an error message saying that the match was forcefully cancelled. And the other players receives a message saying that their items could not be restored.

**Comment by teozfrank** [comment]
What version of spigot and what version of the plugin are you using.

**Comment by teozfrank** [comment]
Closed as no response was made, please create a new issue if you still have this problem.
