### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by WolfMaster333** [teozfrank/DuelMe#40]
Please remove on console - 'give %player% 298 1' very very spam. Sorry for my english.

**Comment by teozfrank** [comment]
I dont know what you mean, could you explain this a little more?

**Comment by JugadorNinja** [comment]
thats due to essentials giving items to a player by console

**Comment by teozfrank** [comment]
This "spam" its a normal console response when a player is given an item, you need to provide more details, please reopen an issue if you have further problems.
