### ISSUE TITLE
Floor

### ISSUE THREAD

**Issue by JugadorNinja** [teozfrank/DuelMe#41]
why do we sometimes spawn inside the floor? D;  the plugins workds great but there are repetitive times when we spawn inside the floor

**Comment by JugadorNinja** [comment]
plus sometimes we appear in the same spawn points :/

**Comment by teozfrank** [comment]
You must have setup the plugin incorrectly causing you to spawn in the ground. Are you using spawnpoints or letting the plugin choose a random location within the arena?

**Comment by JugadorNinja** [comment]
im using 2 spawnpoints on all 15 arenas.  sometimes they work good but sometimes in spawns in the ground.

**Comment by JugadorNinja** [comment]
when i appear in the underground is when both players appear in the spawnpoint1  but one appears in the right location, but the other appears underground beneath the spawnpoint1

**Comment by teozfrank** [comment]
Please try the latest version of the plugin.

**Comment by JugadorNinja** [comment]
not fixed :/ we are still spawning inside the floor  sometimes, i even tried to put the spawn points in the air

**Comment by gogobebe2** [comment]
I can't reproduce.

**Comment by teozfrank** [comment]
Please test this with worldedit and duelme, no other plugins @JugadorNinja. Also try stopping your server, deleting the arenas config and create one arena and test it again.

**Comment by JugadorNinja** [comment]
i use lastest versions of those two plugins. can you make this: is a player moves it gets send back to the spawnpoints and not only freeze them? like when we are in the floor we try to move it only freeze us from moving, so can you add an option or code so we get send back to the spawnpoints

**Comment by teozfrank** [comment]
Latest version doesnt freeze the players, players are surrounded by blocks in the spawnpoint which are removed when the duel starts.

**Comment by JugadorNinja** [comment]
i started using this again and look whats wrong with the last version: http://i.imgur.com/Qh5cdDF.png http://i.imgur.com/8ygFJiD.jpg  does it meant to be like taht? 
if so.. is wrong cuz in the countdown timer users can move and fight while the start countdown is occcuring

**Comment by JugadorNinja** [comment]
ok so the countdown timer i lowered to 3 so the fight starts right away

**Comment by teozfrank** [comment]
Spawnpoints should be in an open area with no obstacles within 5 blocks in each direction.

**Comment by teozfrank** [comment]
Closed as no response was given on issue. If you still find this issue please create a new issue. Thanks.
