### ISSUE TITLE
Not able to PvP

### ISSUE THREAD

**Issue by elitekiller247** [teozfrank/DuelMe#53]
I set up everything right. But people are not able to attack each other. People cant damage or hurt each other and it is really annoying.

**Comment by teozfrank** [comment]
Would help if you told me more? have you PVP enabled? Have you any plugins that can prevent PVP such as PVPTimer or CombatLog?

**Comment by elitekiller247** [comment]
Yes PVP is enabled. And I have CombatLog on the server


On Mon, Mar 21, 2016 at 6:06 PM, Frank Fallon <notifications@github.com>
wrote:

> Would help if you told me more? have you PVP enabled? Have you any plugins
> that can prevent PVP such as PVPTimer or CombatLog?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/teozfrank/DuelMe/issues/53#issuecomment-199527234>
>



-- 
josh

**Comment by elitekiller247** [comment]
Yes PVP is enabled. And I have CombatLog on the server

**Comment by teozfrank** [comment]
Create your arenas on a seperate world and disable combat log in it.

**Comment by teozfrank** [comment]
Closed as this issue is not an issue with duelme but a conflicting plugin causing teleports to be cancelled.
