### ISSUE TITLE
New Feature Suggestion

### ISSUE THREAD

**Issue by ClankyPoo** [teozfrank/DuelMe#55]
The feature I have thought of is what about more than just 2 people in a duel.

**Comment by teozfrank** [comment]
Explain to me how that would work?

**Comment by ClankyPoo** [comment]
2v2 etc

**Comment by teozfrank** [comment]
thats a little vague, have you a plugin such as factions, clans or something simular? how about dueling different factions or clans?

**Comment by teozfrank** [comment]
Closing as no response made, please re-create this suggestion if you have any follow ups.
