### ISSUE TITLE
Suggestion: 1.8 support?

### ISSUE THREAD

**Issue by xNuxxy** [teozfrank/DuelMe#61]
This plugin is obviously geared towards PvP servers, why is there no 1.8 support? lots of PvP servers are still 1.7/1.8 for various reasons. My players are constantly telling me to get a 1v1 plugin, but O simply can't because they are not good, or not supported.

**Comment by NegroBallz** [comment]
Where is the download for 1.8?

**Comment by teozfrank** [comment]
Here -> https://www.spigotmc.org/resources/duelme-beta-spigot-1-8-8-1-9-4-1-10-0-only.541/download?version=100258
