### ISSUE TITLE
1.8.8 doesn't work for me 

### ISSUE THREAD

**Issue by nitramleo** [teozfrank/DuelMe#64]
Hey when i use it on 1.8 it does not work is there any plugins that will conflict with the plugin?

Regards

**Comment by teozfrank** [comment]
Please be more specific than "it doesnt work", post errors the exact version of spigot you are using.

**Comment by nitramleo** [comment]
i dont get any errors in the console after looking trough 1 hour worth of logs

i only get this when i type /plugins  https://gyazo.com/5f4896de5ce7e7b175e4775260c8b35c 

and i use custom spigot 1.8 / custom jar file 

Regards

**Comment by teozfrank** [comment]
This should be fixed now in the latest update on spigot.
