### ISSUE TITLE
Bug? 

### ISSUE THREAD

**Issue by NitsanDA** [teozfrank/DuelMe#65]
Hello, I have been playing around with your plugin and came across something I feel should be looked into. Apparently when set to "seperateinventories=false" both duelers get taken into the game with their current armour and weapons. Now thats completely fine and all but the issue that I see is that the loosing player will simply loose all their inventory and I think that is a bit unfair.  I believe you should either fix it so neither loose anything or make it so when the player gets killed their items get dropped and there is time after the match (Like 10 - 20 seconds) for the victor to loot the drops. 
This is merely a suggestion but I really would appreaciate a fix. 

Thank you in advance!

**Comment by teozfrank** [comment]
This is not a bug, its intentional. But it might be a good suggestion to let the winner get the loot or what I was thinking was to have a duel chest that if someone wins they can access the chest and get the loot from there when they win a duel.

**Comment by NitsanDA** [comment]
That could probably work too. I would suggest that it would be toggleable in the config "chestloot=true/false" or something along those lines and make is so if its set to false that at the end of the match no one looses anything and the winner gets a prize. 

Also on another note: I saw a review on the main plugin page asking about allies and teammates or something not being able to duel and you suggested they disable the plugin in that world. Wondering how one would go about doing a thing like that as I think I would encounter the same issue with the server im planning to run this plugin on - Factions. 
I doubt you would really know something but any useful tips would help! Thanks again.

**Comment by teozfrank** [comment]
Most plugins like factions, towny, combat log etc  that would interfere with this plugin  you can disable the plugin on certain worlds so that it would not interfere with it. Just create your arenas on a seperate world and disable that plugin in that world so duels can take place with no interferance.

**Comment by NitsanDA** [comment]
Thanks for your help my friend! I really appreciate it. As for the main DuelMe plugin, are you going to be creating what we discussed earlier? And if you are, how long should I expect to wait before adding this to my server? Just need any form of (more or less) ETA. 
Thanks a bunch for your awesome support so far! Appreciated.

**Comment by teozfrank** [comment]
Not anytime soon as I literally have no spare time, if a player dies and you dont want them to loose their inventory, there is a Minecraft setting that allows keeping of inventories on death. Now if this is such a concern then maybe using kits instead might be an option instead.

**Comment by teozfrank** [comment]
Just making a note here to add a delay when the losing player dies so the winner can grab the loot. Wow this issue is quite old!
