### ISSUE TITLE
Cant delete arena's

### ISSUE THREAD

**Issue by IronGuest** [teozfrank/DuelMe#67]
I need help,, I deleted configs in plugins folder and restarted and it still reloads same file with all 5 arena's, I had 5 arena's set up but now only two,,, cant delete old ones. I completely removed the plugin and its configs, restarted server and checked /plugins to make sure it was gone and redownloaded from site and reinstalled. I started up server and guess what,, All arena's is still there.. I even tried /dueladmin remove [arena name] and it removes it but after a restart of server, all arena's come back,,,,, Please help,, server is lost right now,,, Even /dueladmin reload re-add's all arena's

**Comment by teozfrank** [comment]
stop the server completely, delete the arenas then start the server.
