### ISSUE TITLE
Winner not teleported back to spawn

### ISSUE THREAD

**Issue by SteveTheDog** [teozfrank/DuelMe#68]
Hello,
If you win a duel, you are not teleported back to the server spawnpoint.

DuelMe version:

**Comment by SteveTheDog** [comment]
Sorry, on my phone and hit comment.

DuelMe version: 0.16.2
Spigot version: 1.8.8 last release

**Comment by teozfrank** [comment]
You have a plugin thats preventing the teleportation such as combatlog or simular, its not a bug, disable combat log in the world you have your arenas (ideally they should be on a seperate world)

**Comment by SteveTheDog** [comment]
Oh, forgot about that; thank you!

**Comment by teozfrank** [comment]
No problem.
