### ISSUE TITLE
Error Log When Starting Arena

### ISSUE THREAD

**Issue by Satelliting** [teozfrank/DuelMe#69]
27.07 12:20:56 [Server] WARN at java.lang.Thread.run(Thread.java:745)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
27.07 12:20:56 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.07 12:20:56 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
27.07 12:20:56 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
27.07 12:20:56 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
27.07 12:20:56 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
27.07 12:20:56 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
27.07 12:20:56 [Server] WARN at com.github.teozfrank.duelme.commands.DuelAdminExecutor.onCommand(DuelAdminExecutor.java:189)
27.07 12:20:56 [Server] WARN at com.github.teozfrank.duelme.commands.admin.ForceDuel.run(ForceDuel.java:49)
27.07 12:20:56 [Server] WARN at com.github.teozfrank.duelme.util.DuelManager.startDuel(DuelManager.java:454)
27.07 12:20:56 [Server] WARN at com.github.teozfrank.duelme.util.MessageManager.getDuelStartMessage(MessageManager.java:46)
27.07 12:20:56 [Server] WARN at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)
27.07 12:20:56 [Server] WARN java.lang.NullPointerException
27.07 12:20:51 [Server] INFO [Info] Successfully loaded 1 Duel Arena(s).
27.07 12:20:51 [Server] INFO [Info] Successfully saved 1 Duel Arena(s).

**Comment by teozfrank** [comment]
Please try a newer version and recreate this issue if it still persists.
