### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by johandrex** [teozfrank/DuelMe#7]
Sometimes you receive a message saying that the arenas is full evens though nobody are in the arena(s). And sometimes the fighters spawns in the exact same spot spawnpoint spot.

**Comment by teozfrank** [comment]
Closed as no response was made.

**Comment by teozfrank** [comment]
Unlocked and reopened due to second issue being present with players being teleported to the same locations.

**Comment by teozfrank** [comment]
I have tested this earlier and can confirm it teleports players to the right spawnpoints, You could have possilbly set both spawnpoints in the same location, if this problem still occurs please create a new issue. Thanks.
