### ISSUE TITLE
Bows sometimes vanish from user's inventory

### ISSUE THREAD

**Issue by Kruize1** [teozfrank/DuelMe#71]
Set up a kit with pvp items, 1 item is a bow.

Users often complain their bow vanishes from their inventory during the duel.

**Comment by teozfrank** [comment]
Users claiming this isn't enough I need to know how this is reproduced. In other words step me through step by step on how this happens. Also if you could provide the kit details that would help too. Is it an essentials kit or just items given via single commands? If you don't know how to reproduce it, a demonstration of this happening would help too.

**Comment by Kruize1** [comment]
I checked and maybe this isn't using a kit?

Here are the item details from the config:

  duelstart:
          - 'give %player% 302 1'
          - 'give %player% 303 1'
          - 'give %player% 304 1'
          - 'give %player% 305 1'
          - 'give %player% 268 1'
          - 'give %player% 261 1'
          - 'give %player% 262 15'


The issue only happens sometimes. I would say possibly 1/10 times.

Steps are pretty straightforward, but you may need multiple users to repro the issue:
1. Send duel request to User A
2. Accept duel request on User B
3. Check inventory
4. Wait for timer to reach 0 and Duel Start
5.  Check inventory again

**Comment by teozfrank** [comment]
No its not, could you try adding these items to an essentails kit and see does the same thing happen?

**Comment by Kruize1** [comment]
I think this might have been a knock on bug from the other issue, where there's 2 arenas in the same location. 

Honestly, after fixing the arena so there's only 1, the disappearing items issue has not occurred.

I'll close this for now, and if the issue occurs again, I can re-open this.
