### ISSUE TITLE
Player death messages are not replacing %player% correctly

### ISSUE THREAD

**Issue by initsuj** [teozfrank/DuelMe#74]
String deathMessageByOther = mm.getKillOtherMessage();
deathMessageByOther = deathMessageByOther.replaceAll("%player%", deathMessageByOther);
e.setDeathMessage(fm.getPrefix() + deathMessageByOther);

I believe the correct code should be:
deathMessageByOther = deathMessageByOther.replaceAll("%player%", playerName);

Otherwise, it shows up as 
%player% was killed in a duel! was killed in a duel!

**Comment by teozfrank** [comment]
Does this still occur?

**Comment by AndrewRed67** [comment]
I have the same issue, so it still occurs.

**Comment by teozfrank** [comment]
Fixed, please update to the latest updated version 0.17.4 
https://www.spigotmc.org/resources/duelme-beta-spigot-1-8-8-1-11-2-only.541/update?update=137319
