### ISSUE TITLE
Gets Errors on Spigot 1.11.2

### ISSUE THREAD

**Issue by IronGuest** [teozfrank/DuelMe#81]
20.01 14:19:13 [Server] ERROR Could not pass event InventoryClickEvent to DuelMe v0.17.4
20.01 14:19:13 [Server] INFO org.bukkit.event.EventException
20.01 14:19:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1839) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
20.01 14:19:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
20.01 14:19:13 [Server] INFO Caused by: java.lang.NullPointerException
20.01 14:19:13 [Server] INFO at com.github.teozfrank.duelme.menus.AcceptMenu.onInventoryClick(AcceptMenu.java:75) ~[?:?]
20.01 14:19:13 [Server] INFO at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?]
20.01 14:19:13 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
20.01 14:19:13 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
20.01 14:19:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-0b1090d-7fdc749]
20.01 14:19:13 [Server] INFO ... 15 more

**Comment by teozfrank** [comment]
Posting just a console log is useless if you dont tell me when this happens.

**Comment by teozfrank** [comment]
Latest version should fix this, please re-open if it still occurs.
