### ISSUE TITLE
Potion Effect

### ISSUE THREAD

**Issue by PyroFT** [teozfrank/DuelMe#82]
When someone starts a duel and they pot and gap. The players keeps potion effects when they leave or  win. People are abusing this by doing /duel and then leaving the duel and pvping with the gap affect. Please fix asap thank you!

**Comment by PyroFT** [comment]
Also if you are in combat in the arena when you get kicked for lets say false hacking it kills you twice so you lose your stuff ingame.

**Comment by PyroFT** [comment]
Hello? can you please fix the potion effect issue? or do i need to use another plugin?

**Comment by teozfrank** [comment]
Excuse me but I am not at your service, I will fix this as soon as I get time to, thanks.

**Comment by PyroFT** [comment]
I understand your not at my service. I was just trying to inform you about an issue that your plugin is having.

**Comment by teozfrank** [comment]
You informed me by creating the issue, I will get to it as soon as I can please be patient.

**Comment by PyroFT** [comment]
I am sorry to bother you again, but when will this fix be applied?

**Comment by teozfrank** [comment]
As I said when I get time.

**Comment by teozfrank** [comment]
This has been fixed in the latest version on spigot, please update.
