### ISSUE TITLE
I can't add/remove rewards for winner and Starting Items

### ISSUE THREAD

**Issue by MamaTata2004** [teozfrank/DuelMe#85]
# do not touch the config version below, it will break the plugin!
configversion: 1.7
duelme:
    checkforupdates: true
    mysql:
       enabled: false
       host: 'localhost'
       port: '3306'
       database: 'duelmestats'
       user: 'user'
       pass: 'pass'
    duel:
       countdowntime: 10
       dueltime: 120
       seperateinventories: true 
       rightclicktoduel: false
       dropitemsondeath: false
       guimenuenabled: true
       surroundmaterial: BARRIER
    announce:
       duelstart: true
       deaths: true
       leavejoin: true
    commands:
       duelstart:
           -
           -
           - 
       duelwinner:
          - 'give %player% 388 32'
          - 'give %player% 264 32
          - 'eco give %player% 500'
          - 'spawn %player%'
    debug:
       enabled: false

I put that on my config
I restarted serven

And when i started a duel withsomeone
I recived leader armor and wooden sword
And winner recived iron sword 

How to to to give me nothing at start
And winner to get diamonds emeralds money and to go to spawn

**Comment by teozfrank** [comment]
for duelstart change it to:

duelstart: []
duelwinner:
- 'give %player% 388 32'
- 'give %player% 264 32
- 'eco give %player% 500'
- 'spawn %player%'

and so on...

**Comment by teozfrank** [comment]
Any update?

If I dont get a response I will have to close this.

**Comment by teozfrank** [comment]
Closed as no response made, please re-create this issue if it persists thanks.
