### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Loonyy** [teozfrank/DuelMe#89]
https://pastebin.com/hRgJkFe1

**Comment by teozfrank** [comment]
What were you doing when this happened? Were there any other errors? Please don't just paste an error and leave it at that. You need to specify more than that! What version of spigot are you using?

**Comment by Loonyy** [comment]
- Sent someone a duel request
- Spigot 1.11

Sorry, was in a rush so had to just post

**Comment by teozfrank** [comment]
Ok I will have to look into this and see can I re-produce the error.

**Comment by teozfrank** [comment]
Closing, Please try the latest version on spigot https://www.spigotmc.org/resources/duelme-beta-spigot-1-8-8-1-12-2-only.541/update?update=204634. If this issue still persists please re-create this issue, thanks.
