### ISSUE TITLE
duel arenas not saving

### ISSUE THREAD

**Issue by ToxicWaste** [teozfrank/DuelMe#9]
Using the wand selecting the arena then using the command /dueladmin create (arena)
works fine and as long as you dont restart or do the reload command the arena stays..
after a reboot or reload it says no arenas.go to the config file for arenas lists the arena like this.
shouldnt it also list the co-ords of the w/e selection

# do not touch the config version below, it will break the plugin!
configversion: 1.0
duelarenas: pvp

**Comment by teozfrank** [comment]
Is this still the case with the latest version?

**Comment by ToxicWaste** [comment]
ill check tomorrow bed time now

**Comment by teozfrank** [comment]
Any update on this? I can verify that it works on my end with the latest version.

**Comment by teozfrank** [comment]
As no reply was made I will assume that this has been fixed, if not please recreate the issue, Thanks.
