### ISSUE TITLE
Arenas getting deleted?

### ISSUE THREAD

**Issue by Dinoosawruss** [teozfrank/DuelMe#90]
Hello. My arenas are getting deleted every day they work for 20 mins and then they just simply get removed and the plugin says that there are no available arenas

Console Errors - None

Other Errors - None

**Comment by teozfrank** [comment]
What version are you using?

Please step me through, step by step on how to re-produce this problem and I will look into it.

**Comment by Dinoosawruss** [comment]
I am using the latest version

There is no way to re-produce the problem. One minute the arena works next minute it is deleted

**Comment by teozfrank** [comment]
Please update to the latest version of the plugin. If the issue still persists please create a new issue thanks.
