### ISSUE TITLE
Duels without arenas

### ISSUE THREAD

**Issue by MrHumblePie** [teozfrank/DuelMe#91]
Was asked to put this here...

So it would be good for players to be able to duel without needing arenas. 

Would also be nice if admins can fully customise the challenge gui. 

:)

**Comment by Sidious82** [comment]
YES!  100% AGREE!  PLEASE DO THIS!

**Comment by teozfrank** [comment]
How would this be controlled? What if other players are in the area?

**Comment by MrHumblePie** [comment]
Sorry mate, its been so long I dropped the plugin and moved to something else.

**Comment by Sidious82** [comment]
bummer...  this would still be a very relevant and useful plugin to have.  just sayin  :)

**Comment by Sidious82** [comment]
re: teozfrank - eliminate the arenas all together.  give players the ability to open a duel and carry the fight anywhere in the world that isnt under claim protection and let the duels commence!

**Comment by teozfrank** [comment]
Sorry but as of now I dont see this is as a viable option. If you can provide to me an example of an existing system that does this without arenas or a viable answer to my previous question I might consider it. Other than that I am closing this issue. If you want to continue its conversation please reply and address the points I have made above, thanks.
