### ISSUE TITLE
Duel update?

### ISSUE THREAD

**Issue by SwiftliciousMV** [teozfrank/DuelMe#92]
hey! So you said to post suggestions here so here I go.. 

a duel update that works similar to the cosmicpvp one I have like a detailed description of all features for you:

Some of the features may already be added 

so basically explaining the GUI format of what happens after a player types /duel <player> this will open and it will show up in this order for the person who starts the duel to choose from:
Allowing them to choose a Arena
Allowing them to choose a kit - preset in the config as already but also adding a option to that GUI to skip the kit section by using your own inventory (prefer to be a chest icon)
Allowing them to set their wagers (exp, items or money [Vault Eco]) (Also allowing them to choose if they want to use givebacks)
and then a GUI to set the rules of their duels (listed in number 4 [you can be creative with the icons per rule but if you want to preset them I added a list of icons next to them]) You can set these to disabled or enabled for them to work. when disabled I would like for it to show as a barrier block however :).
at the last slot of the last row that the rules are on I would like to be a map saying to 'Send Duel Request!' in &a (lime) as a empty map for the icon.

1. Allowing them to actually choose between using their own inventory and a custom kit for duels.
2. Allowing a betting/wager option to bet items, exp & money (Vault) and the winner will get the items bet (including their own items and the loser's items back).
3. A firework at the end for the winner
4. A section to choose what to have enabled/disabled for your duel like for example.. only the person who started the duel can edit these
- Melee Combat (Swords) [Diamond Sword]
- Axe Combat (Axe) [Diamond Axe]
- Ranged Combat (Bows [Includes arrow types]) [Bow]
- Unarmed Combat (Fists) [Stick]
- Flight (Elytras and /fly) [Elytra]
- Repairing (/fix or /repair) [Anvil]
- Potions (Regular Potions & Splash Potions & Lingering Potions and when they do a duel it will remove any current potion effects on them) [Splash Potion of Healing]
- Golden Apples & Enchanted Golden Apples (Will remove the effects if they have it before the duel starts) [Golden Apple]
- Enderpearls [Enderpearl]
- Chorus Fruit [Chorus Fruit]
- Totem of Undying [Totem of Undying]
- Shields [Shield]
- Fishing Rods [Fishing Rods]
- Eggs [Egg]
- Fireballs [Fireball]
- Snowballs [Snowball]
- Hunger Loss [Steak]
- Specific Armor pieces:
* Helmet (will disable any type) [Diamond Helmet]
* Chestplate (will disable any type) [Diamond Chestplate]
* Leggings (will disable any type) [Diamond Leggings]
* Boots (will disable any type) [Diamond Boots]
- Health Regeneration [Rose Red Dye]
- Wolves [Wolf Spawn Egg]
- Explosions (TnT & Creepers) [TNT]
- If this is possible.. Vanilla Enchantments (but they get reapplied on duel end) [Enchanted Book]
5. Allow them to duel for givebacks like they will get their items back if they lose or win. (unless it's a kit, only if they decide to use their own inventory).
6. Give rewards for winning duels and support custom items (custom lores and names basically and if possible vanilla enchants)
7. Teleport delay to duel and starting countdowns.
8. with /duel <player> and the player who is dueled will get a duel request and when they hover over the message saying "<Player> wants to duel here! Click here to accept!" will accept the duel.
9. Allow how many rounds you fight each other in: options being 1, 3 or 5.
10. Save health, exp, hunger bar, potion effects, last known location and inventory from before duel started if using kits.
11. Disable God mode, fly mode, vanish mode, set to survival, etc on duel.
12. Hook in with CombatLogPlus () so if they are in combat they can't duel.
13. Heal players before duels, remove any potion effects they have before the duel & fill their hunger bars.
14. Allow at the end of the match for the players to view each other's inventories like a hover message for the winner's inventory and the loser's inventory to see their armor enchants, durability, etc.
15. Works for 1.11.2 version of Minecraft & has 1.9+ sounds implemented for GUI clicking features if possible.
16. Create as many arenas and kits as you want with commands featuring creating them, saving them & deleting them.
17. Toggle duel requests with /duel toggle.
18. View your wins, losses, latest matches and more with /duel stats.
19. Spectate other matches with /spectate.
20. Give rewards for winning duels.
21. Ability to change in-game messages.

**Comment by NathanD2001** [comment]
An antic scan system would also be nice for the betting system so once you confirm you can't change anything
