### ISSUE TITLE
Doesn't work on 1.11

### ISSUE THREAD

**Issue by YunusGG** [teozfrank/DuelMe#95]
Spigot:
https://i.hizliresim.com/zBEYoY.png

**Comment by SirGregg** [comment]
Post the error message(s) you're getting in console.

**Comment by teozfrank** [comment]
You need to be more specific than its not working, Please provide the logs that show it doesnt work too please.

**Comment by teozfrank** [comment]
Closed as no response made. Please create a new issue if this problem persists.
