### ISSUE TITLE
Problem when restart server.

### ISSUE THREAD

**Issue by pjorun** [teozfrank/DuelMe#96]
Hello, i have problem with this plugin when i restart server.
https://gist.github.com/pjorun/f208529fd292146ccffd3bd1eec8867d

On first when i create arena all work fine, but problem is generate when i restart server.
Arena and lobby is on different world.

**Comment by teozfrank** [comment]
Can you provide the contents of your DueMe plugin please, you can remove MySQL login details if needed.

**Comment by pjorun** [comment]
https://gist.github.com/pjorun/7e83eecc42a13edf9d0f4ccb6ba31960

**Comment by teozfrank** [comment]
Can you please check this on the latest version that was just released today?

**Comment by teozfrank** [comment]
I do not see this issue on the latest version. If this still persists please re-create a new issue, thanks.
