### ISSUE TITLE
Magicspells Mana and Losing

### ISSUE THREAD

**Issue by Fawkd** [teozfrank/DuelMe#98]
Hello,

First of all, I would like to thank you for creating such an awesome plugin - it works as it should!
...but, there's one thing that is giving me headache.
I am using Magicspells for well, magic on my server and the mana system within that plugin seems to bug out everytime a person loses a duel (?).
This is not an issue with the magicspells I assume because this doesn't happen if the player dies outside of the duel.
Could there be something like a playerDeathEvent or anything related that might be causing this ?
The mana recharge is done by holding SHIFT key and the mana is represented in the EXP bar.

Regards,
Fawked

**Comment by teozfrank** [comment]
Might be better to setup your arenas on a different world and disable your magicspells plugin there or does the plugin need to be used for dueling?

**Comment by Fawkd** [comment]
Hi,
Thanks for the reply.
Sadly, the MagicSpells plugin is one of the main features on the server. Players are meant to have magic duels and this plugin is amazing for it.
Currently this plugin is the easiest to config and manage overall so I would hate to switch from it, is there anything that can be done to prevent the mana bugging out?
As mentioned, it only happens after losing the duel (dying and getting tpd back to spawn)

**Comment by teozfrank** [comment]
Do you have a link to the magicspells plugin so I can take a look?

**Comment by Fawkd** [comment]
[https://github.com/TheComputerGeek2/MagicSpells/releases](url)

**Comment by teozfrank** [comment]
> that plugin seems to bug out everytime a person loses a duel (?).

Could you please expand on "bug out" what happens that should not when a player loses?

**Comment by Fawkd** [comment]
Okay so what happens after player dies in duel (loses) is that, the specific player is not able to recharge their mana again (Holding SHIFT in my case). This means that the next time they wanna duel right after the duel they lost, they would have to relog or die to fix the problem.
NOTE: This doesn't happen any other way expect them losing in a duel and I cannot find a reason why, which is why I opened the thread!

**Comment by teozfrank** [comment]
Could you please add me on discord as I would like to see this for myself. -> teozfrank

**Comment by Fawkd** [comment]
I would, but to add you I need the #NUMBER I sent you mine in PMs in Spigot
