### ISSUE TITLE
Player stuck!

### ISSUE THREAD

**Issue by CaptainAmpersand** [teozfrank/DuelMe#99]
[Sun, 11. Feb 2018 02:02:01 EST INFO] Ampersand issued server command: /dueladmin reload
[Sun, 11. Feb 2018 02:02:01 EST INFO] [DuelMe] [Debug] End duel by duel arena.
[Sun, 11. Feb 2018 02:02:01 EST INFO] [DuelMe] [Debug] Playercount: 1
[Sun, 11. Feb 2018 02:02:01 EST INFO] [DuelMe] [Debug] One player remains, rewarding.
[Sun, 11. Feb 2018 02:02:01 EST INFO] [DuelMe] [Debug] 1 player left, now rewarding.
[Sun, 11. Feb 2018 02:02:01 EST INFO] [DuelMe] [Debug] null
[Sun, 11. Feb 2018 02:02:01 EST INFO] CONSOLE issued server command: /give NanoNuke 267 1
[Sun, 11. Feb 2018 02:02:01 EST INFO] Giving 1 of iron sword to NanoNuke.
[Sun, 11. Feb 2018 02:02:01 EST WARN] java.lang.NullPointerException

This is after a duel, of course. I'm setting it up. The player will be told that they can't get their player data back, seen @ http://i.nanonuke.net/javaw_2018-02-10_23-05-26.png
(Note that those are individual reloads trying to making it work)
DuelMe version 0.18.3
Spigot 1.12.2, git-Spigot-4bd94dc-aa34e9b

**Comment by CaptainAmpersand** [comment]
More notes: I don't even have the "Giving 1 of iron sword to NanoNuke" enabled in commands. They get spawned back with their items, and the iron sword, with that error, and makes that arena go out of service.

**Comment by teozfrank** [comment]
Are you still having this issue?

**Comment by teozfrank** [comment]
there are some new dev builds which should be more stable,

https://ci.teozfrank.net/job/DuelMe/
